
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.image.ImageFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JScrollBar;
import javax.swing.JViewport;
import javax.swing.filechooser.FileFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Práctica5 extends javax.swing.JFrame {

    /**
     * Creates new form Práctica5
     */
    public Práctica5() {
        initComponents();
        Dimension iDimension;
        iDimension = imagen.getSize();
        iAncho = iDimension.width;
        iAlto = iDimension.height;
        altoImagen.setText(String.valueOf(iAlto));
        anchoImagen.setText(String.valueOf(iAncho));
        
        vista = scroll.getViewport();
        Dimension vDimension;
        vDimension = vista.getExtentSize();
        vAncho = vDimension.width;
        vAlto = vDimension.height;
        altoView.setText(String.valueOf(vAlto));
        anchoView.setText(String.valueOf(vAncho));
        Point p = vista.getViewPosition();
        vX = p.x;
        vY = p.y;
        posXView.setText(String.valueOf(vX));
        posYView.setText(String.valueOf(vY));
        hBar = scroll.getHorizontalScrollBar();
        vBar = scroll.getVerticalScrollBar();
        hBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {

            @Override
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent e) {
                hScrollAdjust(e);
            }
        });
        vBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {

            @Override
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent e) {
                vScrollAdjust(e);
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        imagen = new javax.swing.JLabel();
        autores = new javax.swing.JPanel();
        ale = new javax.swing.JLabel();
        creadoPor = new javax.swing.JLabel();
        eve = new javax.swing.JLabel();
        infoImagen = new javax.swing.JPanel();
        alto = new javax.swing.JLabel();
        ancho = new javax.swing.JLabel();
        altoImagen = new javax.swing.JTextField();
        anchoImagen = new javax.swing.JTextField();
        cursor = new javax.swing.JPanel();
        estadoLabel = new javax.swing.JLabel();
        posXLabel = new javax.swing.JLabel();
        posYLabel = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        cX = new javax.swing.JTextField();
        cY = new javax.swing.JTextField();
        viewport = new javax.swing.JPanel();
        altoLabelView = new javax.swing.JLabel();
        anchoLabelView = new javax.swing.JLabel();
        posXLabelView = new javax.swing.JLabel();
        posYLabelView = new javax.swing.JLabel();
        altoView = new javax.swing.JTextField();
        anchoView = new javax.swing.JTextField();
        posXView = new javax.swing.JTextField();
        posYView = new javax.swing.JTextField();
        barraMenu = new javax.swing.JMenuBar();
        fileItem = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eurofighter.jpg"))); // NOI18N
        imagen.setText("jLabel1");
        imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imagenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imagenMouseReleased(evt);
            }
        });
        imagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                imagenMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imagenMouseMoved(evt);
            }
        });
        scroll.setViewportView(imagen);

        autores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autores", 1, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        ale.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        ale.setText("Alejandro Suárez Ocampo");

        creadoPor.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        creadoPor.setText("Creado Por:");

        eve.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        eve.setText("Bisila Evelin Rodríguez Sosa");

        javax.swing.GroupLayout autoresLayout = new javax.swing.GroupLayout(autores);
        autores.setLayout(autoresLayout);
        autoresLayout.setHorizontalGroup(
            autoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creadoPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(autoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        autoresLayout.setVerticalGroup(
            autoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoresLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eve, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, autoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        infoImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info Imagen", 2, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        alto.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        alto.setText("Alto");

        ancho.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        ancho.setText("Ancho");

        altoImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altoImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoImagenLayout = new javax.swing.GroupLayout(infoImagen);
        infoImagen.setLayout(infoImagenLayout);
        infoImagenLayout.setHorizontalGroup(
            infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ancho))
                .addGap(18, 18, 18)
                .addGroup(infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altoImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(anchoImagen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoImagenLayout.setVerticalGroup(
            infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoImagenLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(anchoImagen))
                    .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cursor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursor", 2, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        estadoLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        estadoLabel.setText("Estado:");

        posXLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        posXLabel.setText("Pos X:");

        posYLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        posYLabel.setText("Pos Y:");

        javax.swing.GroupLayout cursorLayout = new javax.swing.GroupLayout(cursor);
        cursor.setLayout(cursorLayout);
        cursorLayout.setHorizontalGroup(
            cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posXLabel)
                    .addComponent(posYLabel)
                    .addComponent(estadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(cY, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cursorLayout.setVerticalGroup(
            cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posXLabel)
                    .addComponent(cX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posYLabel)
                    .addComponent(cY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viewport", 2, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        altoLabelView.setText("Alto");

        anchoLabelView.setText("Ancho");

        posXLabelView.setText("Pos X:");

        posYLabelView.setText("Pos Y:");

        javax.swing.GroupLayout viewportLayout = new javax.swing.GroupLayout(viewport);
        viewport.setLayout(viewportLayout);
        viewportLayout.setHorizontalGroup(
            viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(anchoLabelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(altoLabelView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(posXLabelView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posYLabelView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posXView, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(anchoView, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altoView, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posYView))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        viewportLayout.setVerticalGroup(
            viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewportLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altoLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anchoLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anchoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posXLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posXView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posYLabelView, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posYView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fileItem.setText("Archivo");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Abrir");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        fileItem.add(open);
        fileItem.add(jSeparator1);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        close.setText("Salir");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        fileItem.add(close);

        barraMenu.add(fileItem);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cursor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(cursor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void scrollComponentResized(java.awt.event.ComponentEvent evt){
        Dimension vDimension;
        vDimension = vista.getExtentSize();
        vAncho = vDimension.width;
        vAlto = vDimension.height;
        altoView.setText(String.valueOf(vAlto));
        anchoView.setText(String.valueOf(vAncho));
    }
    
    private void hScrollAdjust(java.awt.event.AdjustmentEvent e){
        Point p = vista.getViewPosition();
        vX = p.x;
        posXView.setText(String.valueOf(vX));
    }

    private void vScrollAdjust(java.awt.event.AdjustmentEvent e){
        Point p = vista.getViewPosition();
        vY = p.y;
        posYView.setText(String.valueOf(vY));
    }
    
    private void altoImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altoImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altoImagenActionPerformed

    private void imagenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMousePressed
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estado.setText("Presionado");
        Point position = imagen.getMousePosition();
        cX0 = position.x;
        cY0 = position.y;
        p0 = vista.getViewPosition();
    }//GEN-LAST:event_imagenMousePressed

    private void imagenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseReleased
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estado.setText("");
    }//GEN-LAST:event_imagenMouseReleased

    private void imagenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseDragged
        estado.setText("Arrastrado");
        Point position = imagen.getMousePosition();
        xPos = position.x;
        yPos = position.y;
        cX.setText(String.valueOf(xPos));
        cY.setText(String.valueOf(yPos));
        
        Point p = vista.getViewPosition();
        p.x = p0.x - (int)((xPos-cX0)/2.5);
        p.y = p0.y - (int)((yPos-cY0)/2.5);
        if(p.x < 0) p.x = 0;
        if(p.x > iAncho-vAncho) p.x = iAncho - vAncho;
        if(p.y < 0) p.y = 0;
        if(p.y > iAlto-vAlto) p.y = iAlto - vAlto;
        vista.setViewPosition(p);
    }//GEN-LAST:event_imagenMouseDragged

    private void imagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseMoved
        Point position = imagen.getMousePosition();
        xPos = position.x;
        yPos = position.y;
        cX.setText(String.valueOf(xPos));
        cY.setText(String.valueOf(yPos));
    }//GEN-LAST:event_imagenMouseMoved

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(null);
        FileFilter f = new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {             
                    return true;
                }         
                String filename = f.getName();
                int dot = filename.lastIndexOf('.');
                String extension = filename.substring(dot + 1);

                if (extension != null) {             
                    if( extension.equals("tiff") ||                 
                        extension.equals("tif") ||                 
                        extension.equals("gif") ||                 
                        extension.equals("jpeg") ||                 
                        extension.equals("jpg") ||                 
                        extension.equals("png")) {                     
                        return true;             
                    } else {                 
                        return false;             
                    }        
                }           
                return false; 
            }

            @Override
            public String getDescription() {
                return "Ficheros de Imagenes";
            }
        };
        fileChooser.addChoosableFileFilter(f);
        int retorno = fileChooser.showOpenDialog(open);
        
        if (retorno == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            imagen.setIcon(new javax.swing.ImageIcon(file.getAbsolutePath()));
        }
        
    }//GEN-LAST:event_openActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Práctica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Práctica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Práctica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Práctica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Práctica5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ale;
    private javax.swing.JLabel alto;
    private javax.swing.JTextField altoImagen;
    private javax.swing.JLabel altoLabelView;
    private javax.swing.JTextField altoView;
    private javax.swing.JLabel ancho;
    private javax.swing.JTextField anchoImagen;
    private javax.swing.JLabel anchoLabelView;
    private javax.swing.JTextField anchoView;
    private javax.swing.JPanel autores;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JTextField cX;
    private javax.swing.JTextField cY;
    private javax.swing.JMenuItem close;
    private javax.swing.JLabel creadoPor;
    private javax.swing.JPanel cursor;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel eve;
    private javax.swing.JMenu fileItem;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel infoImagen;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem open;
    private javax.swing.JLabel posXLabel;
    private javax.swing.JLabel posXLabelView;
    private javax.swing.JTextField posXView;
    private javax.swing.JLabel posYLabel;
    private javax.swing.JLabel posYLabelView;
    private javax.swing.JTextField posYView;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel viewport;
    // End of variables declaration//GEN-END:variables
    private int iAlto, iAncho;
    private int xPos, yPos, cX0, cY0;
    private JViewport vista;
    private int vAncho, vAlto, vX, vY;
    private JScrollBar hBar, vBar;
    private Point p0;
}